### ISSUE TITLE
Merge client and server code into this repo?

### ISSUE THREAD

**Issue by bestander** [carabus/arrow-tracker#6]
It would be easier to sync these two if the source code in one place.
Also you could deploy to a single web server both client and server because they are both Node.js and save on deployment costs

**Comment by bestander** [comment]
There is a guide how you can preserve commit history https://saintgimp.org/2013/01/22/merging-two-git-repositories-into-one-repository-without-losing-file-history/

**Comment by carabus** [comment]
Thanks for suggestion, I agree, It is going to be much easier to manage in terms of deployment.

**Comment by carabus** [comment]
fixed in 15872c8
