### ISSUE TITLE
Support non olympic target types

### ISSUE THREAD

**Issue by bestander** [carabus/arrow-tracker#7]
In my shooting range I don't have Olympic targets but have either one color NFAA ones https://shootingtime.com/archery/nfaa-300-round/ or 40cm FITA https://www.canadaarcheryonline.com/products/fita-vegas-target-face.

Can you support those?

**Comment by carabus** [comment]
hey, @bestander, you are welcome to create a pull request for this.

**Comment by carabus** [comment]
NFAA target fully supported in c1d40c2

**Comment by carabus** [comment]
I am going to close this. New issue should be created for each target type.
